CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch \
--nproc_per_node=2 \
--master_port 12325 \
downstream_phase/run_phase_training.py \
--batch_size 64 \
--epochs 50 \
--save_ckpt_freq 10 \
--model  AVT \
--pretrained_path None \
--opt SGD \
--mixup 0.8 \
--cutmix 1.0 \
--smoothing 0.1 \
--lr 1e-4 \
--layer_decay 0.75 \
--warmup_epochs 5 \
--data_path /data/LungRes80 \
--eval_data_path /data/LungRes80 \
--nb_classes 7 \
--data_strategy online \
--output_mode key_frame \
--num_frames 16 \
--sampling_rate 4 \
--data_set LungRes80 \
--data_fps 1fps \
--output_dir /results/LungRes80 \
--log_dir /results/LungRes80 \
--num_workers 24 \
--dist_eval \
--enable_deepspeed \
--no_auto_resume